version: '3'

services:

  jenkins:

    build: .

    container_name: jenkins-server

    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
	  - JAVA_OPTS=-Dhudson.model.DirectoryBrowserSupport.CSP=""

    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    depends_on:
      - selenium



  selenium:

    image: selenium/standalone-chrome:latest

    container_name: selenium

    ports:
      - "4444:4444"

    shm_size: 2gb

    environment:
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true



volumes:

  jenkins_home:
